#spring:
#  application:
#    name: payment-service
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5433/db_payments?useSSL=false
#    username: fazt2
#    password: 123456
#  kafka:
#    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      acks: all
#      properties:
#        delivery.timeout.ms: 120000
#        linger.ms: 0
#        request.timeout.ms: 30000
#        max.in.flight.requests.per.connection: 5
#        enable.idempotence: true
#        allow.auto.create.topics: false
#    consumer:
#      group-id: payments-ms-angieBraids
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: 'com.braidsbeautybyangie.*'
#        allow.auto.create.topics: false
#    admin:
#      auto-create: false
#
#payments:
#  commands:
#    topic:
#      name: payments-commands
#  events:
#    topic:
#      name: payments-events
#
#server:
#  port: 0
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.value}
#
#
stripe:
  secret:
    key: sk_test_51SdYNAHMrevbTo0hluIqJLsFsNxAbxOYy4qQquw6LvsTmKsiK13jSLUdf6ExMeCqMlQAKXx6Jz4iDKF134NB5Jh8007xjKWxWe
  publishable:
    key: pk_test_51SdYNAHMrevbTo0hB34XndyOb0O80ZOJXhsRTJlYKKkVnS4s1U4ZkWZV8H0eMPaJLENRpkQ76Qt7jANtFyzRtI0200LaYgs2k7
  currency: pen
  webhook:
    secret: whsec_06e4671138f44db80c6b6a6ec8c72dcf4b2771776f828106d1bc2f65aec7e611